import {
  Employee,
  Department,
  AttendanceRecord,
  LeaveRequest,
  LeaveBalance,
  ActivitySession,
  AppUsage,
  WebUsage,
  AuditLog,
  SecurityAlert,
  Trade,
  NotificationItem,
} from '../types';

export const initialDepartments: Department[] = [
  { id: 'dept-1', name: 'Information Technology', code: 'IT', headName: 'Vikram Malhotra', employeeCount: 48 },
  { id: 'dept-2', name: 'Human Resources', code: 'HR', headName: 'Priya Sharma', employeeCount: 12 },
  { id: 'dept-3', name: 'Finance & Accounts', code: 'FIN', headName: 'Sunita Menon', employeeCount: 20 },
  { id: 'dept-4', name: 'Sales & Marketing', code: 'SLS', headName: 'Rajesh Khanna', employeeCount: 26 },
  { id: 'dept-5', name: 'Operations', code: 'OPS', headName: 'Kavita Reddy', employeeCount: 14 },
  { id: 'dept-6', name: 'Trading & Risk', code: 'TRD', headName: 'Rohan Gupta', employeeCount: 8 },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    empId: 'EMP001',
    fullName: 'Rahul Bajediyal',
    email: 'employee@demo.com',
    phone: '+91 98765 43210',
    departmentId: 'dept-1',
    departmentName: 'Information Technology',
    designation: 'Senior Software Engineer',
    roleName: 'Employee',
    managerName: 'Amit Patel',
    joiningDate: '2024-01-15',
    salary: 58000,
    employmentType: 'Full-Time',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'emp-2',
    empId: 'EMP002',
    fullName: 'Amit Patel',
    email: 'manager@demo.com',
    phone: '+91 98765 43211',
    departmentId: 'dept-1',
    departmentName: 'Information Technology',
    designation: 'Engineering Manager',
    roleName: 'Manager',
    managerName: 'Vikram Malhotra',
    joiningDate: '2022-03-10',
    salary: 120000,
    employmentType: 'Full-Time',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'emp-3',
    empId: 'EMP003',
    fullName: 'Priya Sharma',
    email: 'hr@demo.com',
    phone: '+91 98765 43212',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    designation: 'Lead HR Specialist',
    roleName: 'HR',
    managerName: 'Vikram Malhotra',
    joiningDate: '2023-05-20',
    salary: 75000,
    employmentType: 'Full-Time',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'emp-4',
    empId: 'EMP004',
    fullName: 'Sunita Menon',
    email: 'finance@demo.com',
    phone: '+91 98765 43213',
    departmentId: 'dept-3',
    departmentName: 'Finance & Accounts',
    designation: 'Finance Controller',
    roleName: 'Finance',
    managerName: 'Vikram Malhotra',
    joiningDate: '2022-11-01',
    salary: 110000,
    employmentType: 'Full-Time',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'emp-5',
    empId: 'EMP005',
    fullName: 'Rohan Gupta',
    email: 'trader@demo.com',
    phone: '+91 98765 43214',
    departmentId: 'dept-6',
    departmentName: 'Trading & Risk',
    designation: 'Senior Derivatives Trader',
    roleName: 'Trader',
    managerName: 'Vikram Malhotra',
    joiningDate: '2023-08-14',
    salary: 140000,
    employmentType: 'Full-Time',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'emp-6',
    empId: 'EMP006',
    fullName: 'Aarav Deshmukh',
    email: 'aarav.deshmukh@pavion.demo',
    phone: '+91 98234 11234',
    departmentId: 'dept-1',
    departmentName: 'Information Technology',
    designation: 'Backend Architect',
    roleName: 'Developer',
    managerName: 'Amit Patel',
    joiningDate: '2023-02-11',
    salary: 88000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-7',
    empId: 'EMP007',
    fullName: 'Ananya Iyer',
    email: 'ananya.iyer@pavion.demo',
    phone: '+91 98234 55432',
    departmentId: 'dept-1',
    departmentName: 'Information Technology',
    designation: 'Frontend Lead',
    roleName: 'Developer',
    managerName: 'Amit Patel',
    joiningDate: '2023-04-18',
    salary: 82000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-8',
    empId: 'EMP008',
    fullName: 'Suresh Nair',
    email: 'suresh.nair@pavion.demo',
    phone: '+91 98234 77891',
    departmentId: 'dept-4',
    departmentName: 'Sales & Marketing',
    designation: 'Senior VP Sales',
    roleName: 'Manager',
    managerName: 'Vikram Malhotra',
    joiningDate: '2022-09-01',
    salary: 130000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-9',
    empId: 'EMP009',
    fullName: 'Sneha Joshi',
    email: 'sneha.joshi@pavion.demo',
    phone: '+91 98234 99123',
    departmentId: 'dept-2',
    departmentName: 'Human Resources',
    designation: 'Talent Acquisition Partner',
    roleName: 'HR',
    managerName: 'Priya Sharma',
    joiningDate: '2024-03-01',
    salary: 52000,
    employmentType: 'Full-Time',
    status: 'On Leave',
  },
  {
    id: 'emp-10',
    empId: 'EMP010',
    fullName: 'Varun Kapoor',
    email: 'varun.kapoor@pavion.demo',
    phone: '+91 98234 44321',
    departmentId: 'dept-5',
    departmentName: 'Operations',
    designation: 'Logistics Manager',
    roleName: 'Manager',
    managerName: 'Kavita Reddy',
    joiningDate: '2023-07-22',
    salary: 68000,
    employmentType: 'Full-Time',
    status: 'Absent',
  },
  {
    id: 'emp-11',
    empId: 'EMP011',
    fullName: 'Pooja Hegde',
    email: 'pooja.hegde@pavion.demo',
    phone: '+91 98234 66543',
    departmentId: 'dept-3',
    departmentName: 'Finance & Accounts',
    designation: 'Payroll Accountant',
    roleName: 'Finance',
    managerName: 'Sunita Menon',
    joiningDate: '2023-10-10',
    salary: 48000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-12',
    empId: 'EMP012',
    fullName: 'Aditya Kulkarni',
    email: 'aditya.kulkarni@pavion.demo',
    phone: '+91 98234 88765',
    departmentId: 'dept-6',
    departmentName: 'Trading & Risk',
    designation: 'Quant Risk Analyst',
    roleName: 'Trader',
    managerName: 'Rohan Gupta',
    joiningDate: '2024-02-15',
    salary: 95000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-13',
    empId: 'EMP013',
    fullName: 'Diya Sengupta',
    email: 'diya.sengupta@pavion.demo',
    phone: '+91 98234 12345',
    departmentId: 'dept-1',
    departmentName: 'Information Technology',
    designation: 'QA Automation Engineer',
    roleName: 'Developer',
    managerName: 'Amit Patel',
    joiningDate: '2024-05-10',
    salary: 50000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-14',
    empId: 'EMP014',
    fullName: 'Ishaan Bhatt',
    email: 'ishaan.bhatt@pavion.demo',
    phone: '+91 98234 23456',
    departmentId: 'dept-4',
    departmentName: 'Sales & Marketing',
    designation: 'Business Development Exec',
    roleName: 'Employee',
    managerName: 'Suresh Nair',
    joiningDate: '2024-06-01',
    salary: 42000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
  {
    id: 'emp-15',
    empId: 'EMP015',
    fullName: 'Manish Tiwari',
    email: 'manish.tiwari@pavion.demo',
    phone: '+91 98234 34567',
    departmentId: 'dept-5',
    departmentName: 'Operations',
    designation: 'Procurement Specialist',
    roleName: 'Employee',
    managerName: 'Varun Kapoor',
    joiningDate: '2023-12-05',
    salary: 46000,
    employmentType: 'Full-Time',
    status: 'Active',
  },
];

export const rahulActivitySession: ActivitySession = {
  employeeName: 'Rahul Bajediyal',
  loginTime: '09:12 AM',
  currentSession: '07h 22m',
  activeTime: '06h 41m',
  idleTime: '41m',
  activeMinutes: 401,
  idleMinutes: 41,
  productivityScore: 78,
};

export const rahulAppUsage: AppUsage[] = [
  { appName: 'VS Code', category: 'Development', duration: '3h 20m', durationMinutes: 200, status: 'Productive', percentage: 48 },
  { appName: 'Chrome', category: 'Research & Browsing', duration: '2h 10m', durationMinutes: 130, status: 'Neutral', percentage: 31 },
  { appName: 'Slack', category: 'Team Communication', duration: '45m', durationMinutes: 45, status: 'Productive', percentage: 11 },
  { appName: 'YouTube', category: 'Media', duration: '30m', durationMinutes: 30, status: 'Non-productive', percentage: 7 },
  { appName: 'iTerm2 / Terminal', category: 'DevOps & Git', duration: '15m', durationMinutes: 15, status: 'Productive', percentage: 3 },
];

export const rahulWebUsage: WebUsage[] = [
  { domain: 'github.com', category: 'Code Collaboration', duration: '2h 12m', durationMinutes: 132, status: 'Productive', percentage: 55 },
  { domain: 'google.com', category: 'Documentation & Search', duration: '45m', durationMinutes: 45, status: 'Neutral', percentage: 19 },
  { domain: 'youtube.com', category: 'Video Streaming', duration: '30m', durationMinutes: 30, status: 'Non-productive', percentage: 13 },
  { domain: 'facebook.com', category: 'Social Media', duration: '15m', durationMinutes: 15, status: 'Non-productive', percentage: 6 },
  { domain: 'stackoverflow.com', category: 'Developer Q&A', duration: '18m', durationMinutes: 18, status: 'Productive', percentage: 7 },
];

export const rahulLeaveBalances: LeaveBalance = {
  annual: { total: 14, used: 5, remaining: 9 },
  sick: { total: 10, used: 2, remaining: 8 },
  casual: { total: 8, used: 1, remaining: 7 },
};

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeId: 'emp-1',
    employeeName: 'Rahul Bajediyal',
    empId: 'EMP001',
    departmentName: 'Information Technology',
    leaveType: 'Annual',
    startDate: '2026-10-15',
    endDate: '2026-10-17',
    daysCount: 3,
    reason: 'Attending family wedding ceremony in Uttarakhand',
    status: 'PENDING',
  },
  {
    id: 'leave-2',
    employeeId: 'emp-9',
    employeeName: 'Sneha Joshi',
    empId: 'EMP009',
    departmentName: 'Human Resources',
    leaveType: 'Maternity',
    startDate: '2026-10-01',
    endDate: '2026-12-31',
    daysCount: 90,
    reason: 'Maternity leave as approved by HR',
    status: 'APPROVED',
    approvedBy: 'Priya Sharma (HR Lead)',
    reviewedAt: '2026-09-25',
  },
  {
    id: 'leave-3',
    employeeId: 'emp-7',
    employeeName: 'Ananya Iyer',
    empId: 'EMP007',
    departmentName: 'Information Technology',
    leaveType: 'Sick',
    startDate: '2026-10-09',
    endDate: '2026-10-10',
    daysCount: 2,
    reason: 'Viral fever and medical rest advice',
    status: 'PENDING',
  },
  {
    id: 'leave-4',
    employeeId: 'emp-1',
    employeeName: 'Rahul Bajediyal',
    empId: 'EMP001',
    departmentName: 'Information Technology',
    leaveType: 'Casual',
    startDate: '2026-09-12',
    endDate: '2026-09-12',
    daysCount: 1,
    reason: 'Personal banking and documentation work',
    status: 'APPROVED',
    approvedBy: 'Amit Patel (Manager)',
    reviewedAt: '2026-09-10',
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    empId: 'EMP001',
    employeeName: 'Rahul Bajediyal',
    department: 'Information Technology',
    date: '08 Oct 2026',
    checkIn: '09:12',
    checkOut: '18:03',
    workingMinutes: 490,
    breakMinutes: 45,
    overtimeMinutes: 30,
    status: 'Present',
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    empId: 'EMP002',
    employeeName: 'Amit Patel',
    department: 'Information Technology',
    date: '08 Oct 2026',
    checkIn: '08:55',
    checkOut: '18:15',
    workingMinutes: 510,
    breakMinutes: 50,
    overtimeMinutes: 45,
    status: 'Present',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    empId: 'EMP003',
    employeeName: 'Priya Sharma',
    department: 'Human Resources',
    date: '08 Oct 2026',
    checkIn: '09:25',
    checkOut: '18:00',
    workingMinutes: 470,
    breakMinutes: 45,
    overtimeMinutes: 0,
    status: 'Late',
  },
  {
    id: 'att-4',
    employeeId: 'emp-4',
    empId: 'EMP004',
    employeeName: 'Sunita Menon',
    department: 'Finance & Accounts',
    date: '08 Oct 2026',
    checkIn: '09:05',
    checkOut: '18:10',
    workingMinutes: 495,
    breakMinutes: 50,
    overtimeMinutes: 20,
    status: 'Present',
  },
  {
    id: 'att-5',
    employeeId: 'emp-5',
    empId: 'EMP005',
    employeeName: 'Rohan Gupta',
    department: 'Trading & Risk',
    date: '08 Oct 2026',
    checkIn: '08:45',
    checkOut: '16:30',
    workingMinutes: 435,
    breakMinutes: 30,
    overtimeMinutes: 0,
    status: 'Present',
  },
  {
    id: 'att-6',
    employeeId: 'emp-10',
    empId: 'EMP010',
    employeeName: 'Varun Kapoor',
    department: 'Operations',
    date: '08 Oct 2026',
    checkIn: null,
    checkOut: null,
    workingMinutes: 0,
    breakMinutes: 0,
    overtimeMinutes: 0,
    status: 'Absent',
  },
  {
    id: 'att-7',
    employeeId: 'emp-9',
    empId: 'EMP009',
    employeeName: 'Sneha Joshi',
    department: 'Human Resources',
    date: '08 Oct 2026',
    checkIn: null,
    checkOut: null,
    workingMinutes: 0,
    breakMinutes: 0,
    overtimeMinutes: 0,
    status: 'On Leave',
  },
];

export const initialSecurityAlerts: SecurityAlert[] = [
  {
    id: 'sec-1',
    title: 'Failed Login Attempt',
    description: 'Rahul - 3 failed password attempts detected from IP 192.168.1.189',
    alertType: 'FAILED_LOGIN',
    severity: 'HIGH',
    targetUser: 'Rahul Bajediyal',
    isResolved: false,
    createdAt: 'Today, 11:42 AM',
  },
  {
    id: 'sec-2',
    title: 'External File Sharing',
    description: 'Finance_Report.xlsx shared externally with unauthorized external domain',
    alertType: 'EXTERNAL_SHARE',
    severity: 'CRITICAL',
    targetUser: 'Sunita Menon',
    isResolved: false,
    createdAt: 'Today, 10:21 AM',
  },
  {
    id: 'sec-3',
    title: 'Unauthorized Access',
    description: 'Restricted Payroll Module accessed outside authorized office IP subnet',
    alertType: 'UNAUTHORIZED_ACCESS',
    severity: 'HIGH',
    targetUser: 'System Guest',
    isResolved: false,
    createdAt: 'Today, 09:48 AM',
  },
  {
    id: 'sec-4',
    title: 'Bulk Data Export',
    description: 'Bulk Employee Directory (128 records) exported to CSV format',
    alertType: 'DATA_EXPORT',
    severity: 'MEDIUM',
    targetUser: 'Vikram Malhotra',
    isResolved: true,
    createdAt: 'Yesterday, 06:15 PM',
  },
  {
    id: 'sec-5',
    title: 'Permission Violation',
    description: 'Trader account attempted to modify HR department leave policies',
    alertType: 'PERMISSION_VIOLATION',
    severity: 'LOW',
    targetUser: 'Rohan Gupta',
    isResolved: true,
    createdAt: 'Yesterday, 03:30 PM',
  },
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'aud-1', userName: 'Rahul Bajediyal', action: 'LOGIN_SUCCESS', module: 'Web Portal', details: 'Successful password authentication', ipAddress: '192.168.1.104', device: 'Chrome / macOS', status: 'Success', timestamp: '09:12 AM' },
  { id: 'aud-2', userName: 'Amit Patel', action: 'EXPORT_REPORT', module: 'Payroll', details: 'Exported monthly team overtime sheet', ipAddress: '192.168.1.45', device: 'Safari / macOS', status: 'Success', timestamp: '10:21 AM' },
  { id: 'aud-3', userName: 'Rahul Bajediyal', action: 'FAILED_LOGIN', module: 'Web Portal', details: 'Failed attempt with bad password', ipAddress: '192.168.1.189', device: 'Firefox / Win11', status: 'Failed', timestamp: '11:42 AM' },
  { id: 'aud-4', userName: 'Priya Sharma', action: 'LEAVE_APPROVED', module: 'HR Portal', details: 'Approved annual leave for Rahul (EMP001)', ipAddress: '192.168.1.22', device: 'Chrome / macOS', status: 'Success', timestamp: '12:15 PM' },
  { id: 'aud-5', userName: 'Rohan Gupta', action: 'TRADE_REQUEST', module: 'Trading', details: 'Submitted Buy order for 500 NIFTY 24500 CE', ipAddress: '192.168.1.88', device: 'Chrome / Linux', status: 'Success', timestamp: '01:05 PM' },
  { id: 'aud-6', userName: 'Sunita Menon', action: 'PAYSLIP_GENERATED', module: 'Payroll', details: 'Generated October batch payslips (128)', ipAddress: '192.168.1.66', device: 'Edge / Windows', status: 'Success', timestamp: '02:40 PM' },
  { id: 'aud-7', userName: 'Guest / Unknown', action: 'UNAUTHORIZED_ACCESS', module: 'Security Gateway', details: 'Blocked unauthorized IP access to /api/secrets', ipAddress: '103.21.244.12', device: 'curl/7.88', status: 'Failed', timestamp: '03:10 PM' },
];

export const initialTrades: Trade[] = [
  { id: 'trd-1', tradeCode: 'TRD-9812', traderName: 'Rohan Gupta', symbol: 'NIFTY 24500 CE', type: 'BUY', quantity: 500, entryPrice: 142.50, exitPrice: 188.00, pnl: 22750, status: 'APPROVED', timestamp: 'Today, 09:30 AM' },
  { id: 'trd-2', tradeCode: 'TRD-9813', traderName: 'Rohan Gupta', symbol: 'RELIANCE', type: 'BUY', quantity: 250, entryPrice: 2980.00, exitPrice: 3045.00, pnl: 16250, status: 'APPROVED', timestamp: 'Today, 10:15 AM' },
  { id: 'trd-3', tradeCode: 'TRD-9814', traderName: 'Rohan Gupta', symbol: 'TCS', type: 'SELL', quantity: 100, entryPrice: 4220.00, exitPrice: 4180.00, pnl: 4000, status: 'APPROVED', timestamp: 'Today, 11:20 AM' },
  { id: 'trd-4', tradeCode: 'TRD-9815', traderName: 'Aditya Kulkarni', symbol: 'INFY', type: 'BUY', quantity: 400, entryPrice: 1890.00, exitPrice: 1870.00, pnl: -8000, status: 'APPROVED', timestamp: 'Today, 01:45 PM' },
  { id: 'trd-5', tradeCode: 'TRD-9816', traderName: 'Rohan Gupta', symbol: 'HDFCBANK', type: 'BUY', quantity: 300, entryPrice: 1680.00, exitPrice: null, pnl: 3200, status: 'PENDING', timestamp: 'Today, 02:10 PM' },
  { id: 'trd-6', tradeCode: 'TRD-9817', traderName: 'Aditya Kulkarni', symbol: 'ICICIBANK', type: 'BUY', quantity: 350, entryPrice: 1240.00, exitPrice: null, pnl: 1850, status: 'PENDING', timestamp: 'Today, 03:00 PM' },
];

export const initialNotifications: NotificationItem[] = [
  { id: 'notif-1', title: 'Leave Application Received', message: 'Rahul Bajediyal has requested 3 days of Annual leave.', type: 'INFO', isRead: false, createdAt: '10 mins ago' },
  { id: 'notif-2', title: 'Security Alert: Failed Login', message: '3 failed attempts recorded for user Rahul from IP 192.168.1.189.', type: 'WARNING', isRead: false, createdAt: '25 mins ago' },
  { id: 'notif-3', title: 'October Payslip Ready', message: 'Your payslip for October 2026 has been generated. Net Salary: ₹53,600.', type: 'SUCCESS', isRead: false, createdAt: '1 hour ago' },
  { id: 'notif-4', title: 'Trade Order Approval Request', message: 'Rohan Gupta submitted HDFCBANK Buy order for manager approval.', type: 'INFO', isRead: true, createdAt: '2 hours ago' },
];
